### ISSUE TITLE
null in fan speed

### ISSUE THREAD

**Issue by KoTeD0** [eeeeeio/gnome-shell-extension-nano-system-monitor#7]
version 4, gnome 45.6 fedora 35
null in monitoring even if everything is disabled
![image](https://user-images.githubusercontent.com/47426673/167024137-329ceb41-96e8-4ccf-ada8-2d6cd8ed9b1c.png)
![image](https://user-images.githubusercontent.com/47426673/167024188-b751d719-b7eb-4672-a7ae-1502ec332fc9.png)

**Comment by eeeeeio** [comment]
Fixed,a few hours later there should be an update under logout
