### ISSUE TITLE
Fan speed: hardcoded hwmon path not correct for all systems

### ISSUE THREAD

**Issue by mkalinski** [eeeeeio/gnome-shell-extension-nano-system-monitor#9]
I was unable to get fan speed to display anything other than `-1` by changing the "fan number" option in settings (I have only one fan in sensors, anyway). After inspecting the code, I found it's because of this line:

https://github.com/eeeeeio/gnome-shell-extension-nano-system-monitor/blob/bd59e38882763b7a54f6e4cad92bad3af6f6dba3/src/extension.js#L325

This assumes that `fan_input` files live in directory `hwmon2`, but on my system, they're in `hwmon4`.

Perhaps the `hwmon` number could be made configurable. Or `sensors` command output could be used for this (it's already used for temperature).

**Comment by eeeeeio** [comment]
sure
I will add this config today
